### ISSUE TITLE
docker-compose up --build failed for ecsblog-demo on Ubuntu 22.04

### ISSUE THREAD

**Issue by snowuyl** [aiordache/demos#8]
~/samba/AWS/demos/ecsblog-demo$ docker-compose up --build
Building backend
Sending build context to Docker daemon  4.096kB
Step 1/7 : FROM python:3.7-alpine
 ---> cd2a4f346519
Step 2/7 : WORKDIR /app
 ---> Using cache
 ---> d7a2713b04cc
Step 3/7 : COPY requirements.txt /app
 ---> Using cache
 ---> 5e26a4331325
Step 4/7 : RUN pip3 install -r requirements.txt
 ---> Using cache
 ---> ceaeffece858
Step 5/7 : COPY main.py /app/main.py
 ---> Using cache
 ---> 4c4ceebc0966
Step 6/7 : ENTRYPOINT ["python3"]
 ---> Using cache
 ---> ea0f4de654cb
Step 7/7 : CMD ["/app/main.py"]
 ---> Using cache
 ---> 9dd4316e3ccd
Successfully built 9dd4316e3ccd
Successfully tagged ecsblog-demo_backend:latest

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Building frontend
Sending build context to Docker daemon  3.072kB
Step 1/2 : FROM nginx:alpine
 ---> 804f9cebfdc5
Step 2/2 : COPY nginx.conf /etc/nginx/conf.d/default.conf
 ---> Using cache
 ---> 484f90419a52
Successfully built 484f90419a52
Successfully tagged ecsblog-demo_frontend:latest

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Starting ecsblog-demo_backend_1 ... done
Starting ecsblog-demo_frontend_1 ... done
Attaching to ecsblog-demo_backend_1, ecsblog-demo_frontend_1
backend_1   | Traceback (most recent call last):
backend_1   |   File "/app/main.py", line 1, in <module>
backend_1   |     from flask import Flask
backend_1   |   File "/usr/local/lib/python3.7/site-packages/flask/__init__.py", line 14, in <module>
backend_1   |     from jinja2 import escape
backend_1   | ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.7/site-packages/jinja2/__init__.py)
frontend_1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
frontend_1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
frontend_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
ecsblog-demo_backend_1 exited with code 1
frontend_1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
frontend_1  | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
frontend_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
frontend_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
frontend_1  | /docker-entrypoint.sh: Configuration complete; ready for start up
frontend_1  | 2022/08/24 10:47:16 [emerg] 1#1: host not found in upstream "backend" in /etc/nginx/conf.d/default.conf:4
frontend_1  | nginx: [emerg] host not found in upstream "backend" in /etc/nginx/conf.d/default.conf:4
ecsblog-demo_frontend_1 exited with code 1

**Comment by arvin1408** [comment]
Ran into same error. Update the requirements file with the flask version below and should work.

Flask>=2.2.2
